language: node_js
node_js:
    - "4"
    - "6"
    - "8"
sudo: false
env:
    - FORCE_COLOR=true
before_install:
    - sh ci.sh
script:
    - npm run-script ci
    - npm link
    - "echo optOut: true > ~/.config/configstore/insight-gh.yml"
    - gh
after_success:
    - sh ci-reports.sh
